services:
  - type: web
    name: brailleverse
    runtime: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn braille_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: FIREBASE_DATABASE_URL
        value: https://braille-display-b87be-default-rtdb.asia-southeast1.firebasedatabase.app
      - key: FIREBASE_AUTH_TOKEN
        value: JmfhE3a7bXgX93GxdliKbI3uRbE5DpU2FGi45MZM
      - key: GEMINI_API_KEY
        value: AIzaSyBOsgOQgjI2INSoMIDNXpL9vObNrXJ3iQg
